export const YOUTUBE = 'YOUTUBE';
export const RECORDER = 'RECORDER';
export const FETCH_VIDEOS = 'FETCH_VIDEOS';
export const FETCH_VIDEOS_SUCCESS = 'FETCH_VIDEOS_SUCCESS';
export const FETCH_VIDEOS_FAILURE = 'FETCH_VIDEOS_FAILURE';
export const FETCH_VIDEO = 'FETCH_VIDEOS';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILURE = 'FETCH_VIDEO_FAILURE';
